services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "4000:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - whisprly-network

  # Laravel backend service
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./backend:/var/www/html
    networks:
      - whisprly-network

  # Next.js frontend service
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - whisprly-network
      
  # Redis service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - whisprly-network

  # RedisInsight service
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - whisprly-network   
      
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=whisprly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - whisprly-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - whisprly-network

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP port
    networks:
      - whisprly-network

volumes:
  postgres-data:

networks:
  whisprly-network:
    driver: bridge 